apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  finalizers:
  - snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
  - snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  name: pre-snap
  namespace: default
spec:
  volumeSnapshotClassName: zfspv-snapclass 
status:
  boundVolumeSnapshotContentName: snapshot-pre-snapshot-dataset
  readyToUse: true
