apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio-restored1
  labels:
    name: fio-restored1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fio-restored-testdataset1
  template:
    metadata:
      labels:
        name: fio-restored-testdataset1
    spec:
      containers:
        - resources:
          name: perfrunner
          image: openebs/tests-fio
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "while true ;do sleep 50; done"]
          volumeMounts:
            - mountPath: /datadir
              name: fio-vol
      volumes:
        - name: fio-vol
          persistentVolumeClaim:
            claimName: pvc-restored-testdataset1