apiVersion: v1
kind: PersistentVolume
metadata:
  name: pre-dataset
spec:
  storageClassName: openebs-zfspv
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: zfs.csi.openebs.io
    volumeHandle: pre-dataset
    volumeAttributes:
      datasetName: pre-dataset
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - controlplane
