kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-restored-testdataset1
spec:
  storageClassName: openebs-zfspv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi