apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pre-pvc
spec:
  storageClassName: openebs-zfspv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pre-dataset
