apiVersion: zfs.openebs.io/v1alpha1
kind: ZFSVolume
metadata:
  finalizers:
  - zfs.openebs.io/finalizer
  name: restored-dataset  # should be same as zfs volume name
  namespace: openebs
spec:
  capacity: "2147483648" # size of the volume in bytes
  fsType: zfs
  compression: "off" #test on
  dedup: "off"
  ownerNodeID: worker1 # should be the nodename where ZPOOL is running
  poolName: zfspv-pool # poolname where the volume is present
  volumeType: DATASET # whether it is a DATASET or ZVOL
status:
  state: Ready # state should be Ready as volume is already present