apiVersion: batch/v1
kind: Job
metadata:
  name: snapshot-migration-sender-append-r.cachedData[migrationRequest.Name].PersistantVolume.Name
spec:
  template:
    spec:
      containers:
      - name: zfs-container
        image: thehamdiaz/zfs-ubuntu:v13.0
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: r.cachedData[migrationRequest.Name].ConfigMap.Name
        volumeMounts:
        - name: ssh-keys
          mountPath: "/etc/ssh-key"
          readOnly: true
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: r.cachedData[migrationRequest.Name].Pod.NodeName
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - r.cachedData[migrationRequest.Name].Pod.NodeName
      volumes:
      - name: ssh-keys
        secret:
          secretName: r.cachedData[migrationRequest.Name].Secret.Name
