apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: migration-snapshot-1
  namespace: default
spec:
  source:
    persistentVolumeClaimName: restored-pvc
  volumeSnapshotClassName: migration-vsc
