apiVersion: v1
kind: Pod
metadata:
  name: zfs-pod
spec:
  containers:
    - name: zfs-container
      image: thehamdiaz/zfs-ubuntu:latest
      securityContext:
        privileged: true
  nodeSelector:
    kubernetes.io/hostname: worker1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - worker1
