apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1
  containers:
    - name: rabbitmq
      image: rabbitmq:3.8-management
      ports:
        - containerPort: 5672
        - containerPort: 15672
      env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-access
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-access
              key: password
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: rabbitmq-data-3g
