# RabbitMQ Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-amqp-service
spec:
  type: ClusterIP
  selector: 
    app: rabbitmq # Selector for rabbitmq pods
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-service
spec:
  type: NodePort
  selector: 
    app: rabbitmq # Selector for rabbitmq pods
  ports:
    - name: management 
      port: 15672
      targetPort: 15672
      nodePort: 30672