apiVersion: v1
kind: Pod
metadata:
  name: zfs-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2
  containers:
    - name: zfs-container
      image: alpine
      command:
      - sleep
      args:
      - infinity
      securityContext:
        privileged: true
      volumeMounts:
        - name: zfs
          mountPath: /dev/zfs
  volumes:
    - name: zfs
      hostPath:
        path: /dev/zfs
        type: CharDevice
