apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc1
spec:
  storageClassName: openebs-zfspv
  dataSource:
    name: migration-snapshot-hj2qm
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
