apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-restored-pvc1
spec:
  storageClassName: openebs-zfspv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: my-restored-pv1
